ame: Github Action for LaTeX
description: GitHub Action to compile LaTeX documents
author: Cheng XU
inputs:
  root_file:
    description: The root LaTeX file to be compiled
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.root_file }}
    - ${{ inputs.glob_root_file }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.compiler }}
    - ${{ inputs.args }}
    - ${{ inputs.extra_packages }}
    - ${{ inputs.extra_system_packages }}
    - ${{ inputs.extra_fonts }}
    - ${{ inputs.pre_compile }}
    - ${{ inputs.post_compile }}
    - ${{ inputs.latexmk_shell_escape }}
    - ${{ inputs.latexmk_use_lualatex }}
    - ${{ inputs.latexmk_use_xelatex }}
branding:
  icon: book
  color: blue
