name: MultiLyx2Pdf
description: Github Action for generating pdfs from multiple lyx
author: stephen <stephenzwj@gmail.com>
inputs:
  root_file:
    description: The root lyx fils to be compiled, seperated by comma
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.root_file }}
branding:
  icon: book-open
  color: gray-dark
