name: Export PDF

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.yml"
      - "CODEOWNERS"
    tags:
      - "*"
jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: lyx2pdf/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: vaggeliskls/lyx2pdf:latest
